// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: StateData.proto

package protobuf.java.com.mycompany.blockchain.protobuf;

public interface DataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Data)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string address = 1;</code>
   */
  java.lang.String getAddress();
  /**
   * <code>string address = 1;</code>
   */
  com.google.protobuf.ByteString
      getAddressBytes();

  /**
   * <code>string data = 2;</code>
   */
  java.lang.String getData();
  /**
   * <code>string data = 2;</code>
   */
  com.google.protobuf.ByteString
      getDataBytes();
}
