// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: StateData.proto

package protobuf.java.com.mycompany.blockchain.protobuf;

public interface PagingOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Paging)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string limit = 1;</code>
   */
  java.lang.String getLimit();
  /**
   * <code>string limit = 1;</code>
   */
  com.google.protobuf.ByteString
      getLimitBytes();

  /**
   * <code>string start = 2;</code>
   */
  java.lang.String getStart();
  /**
   * <code>string start = 2;</code>
   */
  com.google.protobuf.ByteString
      getStartBytes();
}
