// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: StateData.proto

package protobuf.java.com.mycompany.blockchain.protobuf;

public interface StateDataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:StateData)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *Data
   * </pre>
   *
   * <code>repeated .Data data = 1;</code>
   */
  java.util.List<protobuf.java.com.mycompany.blockchain.protobuf.Data> 
      getDataList();
  /**
   * <pre>
   *Data
   * </pre>
   *
   * <code>repeated .Data data = 1;</code>
   */
  protobuf.java.com.mycompany.blockchain.protobuf.Data getData(int index);
  /**
   * <pre>
   *Data
   * </pre>
   *
   * <code>repeated .Data data = 1;</code>
   */
  int getDataCount();
  /**
   * <pre>
   *Data
   * </pre>
   *
   * <code>repeated .Data data = 1;</code>
   */
  java.util.List<? extends protobuf.java.com.mycompany.blockchain.protobuf.DataOrBuilder> 
      getDataOrBuilderList();
  /**
   * <pre>
   *Data
   * </pre>
   *
   * <code>repeated .Data data = 1;</code>
   */
  protobuf.java.com.mycompany.blockchain.protobuf.DataOrBuilder getDataOrBuilder(
      int index);

  /**
   * <pre>
   *the head
   * </pre>
   *
   * <code>string head = 2;</code>
   */
  java.lang.String getHead();
  /**
   * <pre>
   *the head
   * </pre>
   *
   * <code>string head = 2;</code>
   */
  com.google.protobuf.ByteString
      getHeadBytes();

  /**
   * <pre>
   *the link
   * </pre>
   *
   * <code>string link = 3;</code>
   */
  java.lang.String getLink();
  /**
   * <pre>
   *the link
   * </pre>
   *
   * <code>string link = 3;</code>
   */
  com.google.protobuf.ByteString
      getLinkBytes();

  /**
   * <pre>
   *the price
   * </pre>
   *
   * <code>.Paging paging = 4;</code>
   */
  boolean hasPaging();
  /**
   * <pre>
   *the price
   * </pre>
   *
   * <code>.Paging paging = 4;</code>
   */
  protobuf.java.com.mycompany.blockchain.protobuf.Paging getPaging();
  /**
   * <pre>
   *the price
   * </pre>
   *
   * <code>.Paging paging = 4;</code>
   */
  protobuf.java.com.mycompany.blockchain.protobuf.PagingOrBuilder getPagingOrBuilder();
}
