// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: StateData.proto

package protobuf.java.com.mycompany.blockchain.protobuf;

/**
 * <pre>
 *of a structured payload type "create,id=00001,itemName=Computer,colour=red,price=1000";
 * </pre>
 *
 * Protobuf type {@code StateData}
 */
public  final class StateData extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:StateData)
    StateDataOrBuilder {
  // Use StateData.newBuilder() to construct.
  private StateData(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private StateData() {
    data_ = java.util.Collections.emptyList();
    head_ = "";
    link_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private StateData(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              data_ = new java.util.ArrayList<protobuf.java.com.mycompany.blockchain.protobuf.Data>();
              mutable_bitField0_ |= 0x00000001;
            }
            data_.add(
                input.readMessage(protobuf.java.com.mycompany.blockchain.protobuf.Data.parser(), extensionRegistry));
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            head_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            link_ = s;
            break;
          }
          case 34: {
            protobuf.java.com.mycompany.blockchain.protobuf.Paging.Builder subBuilder = null;
            if (paging_ != null) {
              subBuilder = paging_.toBuilder();
            }
            paging_ = input.readMessage(protobuf.java.com.mycompany.blockchain.protobuf.Paging.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(paging_);
              paging_ = subBuilder.buildPartial();
            }

            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        data_ = java.util.Collections.unmodifiableList(data_);
      }
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return protobuf.java.com.mycompany.blockchain.protobuf.StateDataOuterClass.internal_static_StateData_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return protobuf.java.com.mycompany.blockchain.protobuf.StateDataOuterClass.internal_static_StateData_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            protobuf.java.com.mycompany.blockchain.protobuf.StateData.class, protobuf.java.com.mycompany.blockchain.protobuf.StateData.Builder.class);
  }

  private int bitField0_;
  public static final int DATA_FIELD_NUMBER = 1;
  private java.util.List<protobuf.java.com.mycompany.blockchain.protobuf.Data> data_;
  /**
   * <pre>
   *Data
   * </pre>
   *
   * <code>repeated .Data data = 1;</code>
   */
  public java.util.List<protobuf.java.com.mycompany.blockchain.protobuf.Data> getDataList() {
    return data_;
  }
  /**
   * <pre>
   *Data
   * </pre>
   *
   * <code>repeated .Data data = 1;</code>
   */
  public java.util.List<? extends protobuf.java.com.mycompany.blockchain.protobuf.DataOrBuilder> 
      getDataOrBuilderList() {
    return data_;
  }
  /**
   * <pre>
   *Data
   * </pre>
   *
   * <code>repeated .Data data = 1;</code>
   */
  public int getDataCount() {
    return data_.size();
  }
  /**
   * <pre>
   *Data
   * </pre>
   *
   * <code>repeated .Data data = 1;</code>
   */
  public protobuf.java.com.mycompany.blockchain.protobuf.Data getData(int index) {
    return data_.get(index);
  }
  /**
   * <pre>
   *Data
   * </pre>
   *
   * <code>repeated .Data data = 1;</code>
   */
  public protobuf.java.com.mycompany.blockchain.protobuf.DataOrBuilder getDataOrBuilder(
      int index) {
    return data_.get(index);
  }

  public static final int HEAD_FIELD_NUMBER = 2;
  private volatile java.lang.Object head_;
  /**
   * <pre>
   *the head
   * </pre>
   *
   * <code>string head = 2;</code>
   */
  public java.lang.String getHead() {
    java.lang.Object ref = head_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      head_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *the head
   * </pre>
   *
   * <code>string head = 2;</code>
   */
  public com.google.protobuf.ByteString
      getHeadBytes() {
    java.lang.Object ref = head_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      head_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int LINK_FIELD_NUMBER = 3;
  private volatile java.lang.Object link_;
  /**
   * <pre>
   *the link
   * </pre>
   *
   * <code>string link = 3;</code>
   */
  public java.lang.String getLink() {
    java.lang.Object ref = link_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      link_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *the link
   * </pre>
   *
   * <code>string link = 3;</code>
   */
  public com.google.protobuf.ByteString
      getLinkBytes() {
    java.lang.Object ref = link_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      link_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PAGING_FIELD_NUMBER = 4;
  private protobuf.java.com.mycompany.blockchain.protobuf.Paging paging_;
  /**
   * <pre>
   *the price
   * </pre>
   *
   * <code>.Paging paging = 4;</code>
   */
  public boolean hasPaging() {
    return paging_ != null;
  }
  /**
   * <pre>
   *the price
   * </pre>
   *
   * <code>.Paging paging = 4;</code>
   */
  public protobuf.java.com.mycompany.blockchain.protobuf.Paging getPaging() {
    return paging_ == null ? protobuf.java.com.mycompany.blockchain.protobuf.Paging.getDefaultInstance() : paging_;
  }
  /**
   * <pre>
   *the price
   * </pre>
   *
   * <code>.Paging paging = 4;</code>
   */
  public protobuf.java.com.mycompany.blockchain.protobuf.PagingOrBuilder getPagingOrBuilder() {
    return getPaging();
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < data_.size(); i++) {
      output.writeMessage(1, data_.get(i));
    }
    if (!getHeadBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, head_);
    }
    if (!getLinkBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, link_);
    }
    if (paging_ != null) {
      output.writeMessage(4, getPaging());
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < data_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, data_.get(i));
    }
    if (!getHeadBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, head_);
    }
    if (!getLinkBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, link_);
    }
    if (paging_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getPaging());
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof protobuf.java.com.mycompany.blockchain.protobuf.StateData)) {
      return super.equals(obj);
    }
    protobuf.java.com.mycompany.blockchain.protobuf.StateData other = (protobuf.java.com.mycompany.blockchain.protobuf.StateData) obj;

    boolean result = true;
    result = result && getDataList()
        .equals(other.getDataList());
    result = result && getHead()
        .equals(other.getHead());
    result = result && getLink()
        .equals(other.getLink());
    result = result && (hasPaging() == other.hasPaging());
    if (hasPaging()) {
      result = result && getPaging()
          .equals(other.getPaging());
    }
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getDataCount() > 0) {
      hash = (37 * hash) + DATA_FIELD_NUMBER;
      hash = (53 * hash) + getDataList().hashCode();
    }
    hash = (37 * hash) + HEAD_FIELD_NUMBER;
    hash = (53 * hash) + getHead().hashCode();
    hash = (37 * hash) + LINK_FIELD_NUMBER;
    hash = (53 * hash) + getLink().hashCode();
    if (hasPaging()) {
      hash = (37 * hash) + PAGING_FIELD_NUMBER;
      hash = (53 * hash) + getPaging().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static protobuf.java.com.mycompany.blockchain.protobuf.StateData parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static protobuf.java.com.mycompany.blockchain.protobuf.StateData parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static protobuf.java.com.mycompany.blockchain.protobuf.StateData parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static protobuf.java.com.mycompany.blockchain.protobuf.StateData parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static protobuf.java.com.mycompany.blockchain.protobuf.StateData parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static protobuf.java.com.mycompany.blockchain.protobuf.StateData parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static protobuf.java.com.mycompany.blockchain.protobuf.StateData parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static protobuf.java.com.mycompany.blockchain.protobuf.StateData parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static protobuf.java.com.mycompany.blockchain.protobuf.StateData parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static protobuf.java.com.mycompany.blockchain.protobuf.StateData parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(protobuf.java.com.mycompany.blockchain.protobuf.StateData prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   *of a structured payload type "create,id=00001,itemName=Computer,colour=red,price=1000";
   * </pre>
   *
   * Protobuf type {@code StateData}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:StateData)
      protobuf.java.com.mycompany.blockchain.protobuf.StateDataOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protobuf.java.com.mycompany.blockchain.protobuf.StateDataOuterClass.internal_static_StateData_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protobuf.java.com.mycompany.blockchain.protobuf.StateDataOuterClass.internal_static_StateData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protobuf.java.com.mycompany.blockchain.protobuf.StateData.class, protobuf.java.com.mycompany.blockchain.protobuf.StateData.Builder.class);
    }

    // Construct using protobuf.java.com.mycompany.blockchain.protobuf.StateData.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getDataFieldBuilder();
      }
    }
    public Builder clear() {
      super.clear();
      if (dataBuilder_ == null) {
        data_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        dataBuilder_.clear();
      }
      head_ = "";

      link_ = "";

      if (pagingBuilder_ == null) {
        paging_ = null;
      } else {
        paging_ = null;
        pagingBuilder_ = null;
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return protobuf.java.com.mycompany.blockchain.protobuf.StateDataOuterClass.internal_static_StateData_descriptor;
    }

    public protobuf.java.com.mycompany.blockchain.protobuf.StateData getDefaultInstanceForType() {
      return protobuf.java.com.mycompany.blockchain.protobuf.StateData.getDefaultInstance();
    }

    public protobuf.java.com.mycompany.blockchain.protobuf.StateData build() {
      protobuf.java.com.mycompany.blockchain.protobuf.StateData result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public protobuf.java.com.mycompany.blockchain.protobuf.StateData buildPartial() {
      protobuf.java.com.mycompany.blockchain.protobuf.StateData result = new protobuf.java.com.mycompany.blockchain.protobuf.StateData(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (dataBuilder_ == null) {
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          data_ = java.util.Collections.unmodifiableList(data_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.data_ = data_;
      } else {
        result.data_ = dataBuilder_.build();
      }
      result.head_ = head_;
      result.link_ = link_;
      if (pagingBuilder_ == null) {
        result.paging_ = paging_;
      } else {
        result.paging_ = pagingBuilder_.build();
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof protobuf.java.com.mycompany.blockchain.protobuf.StateData) {
        return mergeFrom((protobuf.java.com.mycompany.blockchain.protobuf.StateData)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(protobuf.java.com.mycompany.blockchain.protobuf.StateData other) {
      if (other == protobuf.java.com.mycompany.blockchain.protobuf.StateData.getDefaultInstance()) return this;
      if (dataBuilder_ == null) {
        if (!other.data_.isEmpty()) {
          if (data_.isEmpty()) {
            data_ = other.data_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureDataIsMutable();
            data_.addAll(other.data_);
          }
          onChanged();
        }
      } else {
        if (!other.data_.isEmpty()) {
          if (dataBuilder_.isEmpty()) {
            dataBuilder_.dispose();
            dataBuilder_ = null;
            data_ = other.data_;
            bitField0_ = (bitField0_ & ~0x00000001);
            dataBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getDataFieldBuilder() : null;
          } else {
            dataBuilder_.addAllMessages(other.data_);
          }
        }
      }
      if (!other.getHead().isEmpty()) {
        head_ = other.head_;
        onChanged();
      }
      if (!other.getLink().isEmpty()) {
        link_ = other.link_;
        onChanged();
      }
      if (other.hasPaging()) {
        mergePaging(other.getPaging());
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      protobuf.java.com.mycompany.blockchain.protobuf.StateData parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (protobuf.java.com.mycompany.blockchain.protobuf.StateData) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<protobuf.java.com.mycompany.blockchain.protobuf.Data> data_ =
      java.util.Collections.emptyList();
    private void ensureDataIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        data_ = new java.util.ArrayList<protobuf.java.com.mycompany.blockchain.protobuf.Data>(data_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        protobuf.java.com.mycompany.blockchain.protobuf.Data, protobuf.java.com.mycompany.blockchain.protobuf.Data.Builder, protobuf.java.com.mycompany.blockchain.protobuf.DataOrBuilder> dataBuilder_;

    /**
     * <pre>
     *Data
     * </pre>
     *
     * <code>repeated .Data data = 1;</code>
     */
    public java.util.List<protobuf.java.com.mycompany.blockchain.protobuf.Data> getDataList() {
      if (dataBuilder_ == null) {
        return java.util.Collections.unmodifiableList(data_);
      } else {
        return dataBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     *Data
     * </pre>
     *
     * <code>repeated .Data data = 1;</code>
     */
    public int getDataCount() {
      if (dataBuilder_ == null) {
        return data_.size();
      } else {
        return dataBuilder_.getCount();
      }
    }
    /**
     * <pre>
     *Data
     * </pre>
     *
     * <code>repeated .Data data = 1;</code>
     */
    public protobuf.java.com.mycompany.blockchain.protobuf.Data getData(int index) {
      if (dataBuilder_ == null) {
        return data_.get(index);
      } else {
        return dataBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     *Data
     * </pre>
     *
     * <code>repeated .Data data = 1;</code>
     */
    public Builder setData(
        int index, protobuf.java.com.mycompany.blockchain.protobuf.Data value) {
      if (dataBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDataIsMutable();
        data_.set(index, value);
        onChanged();
      } else {
        dataBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     *Data
     * </pre>
     *
     * <code>repeated .Data data = 1;</code>
     */
    public Builder setData(
        int index, protobuf.java.com.mycompany.blockchain.protobuf.Data.Builder builderForValue) {
      if (dataBuilder_ == null) {
        ensureDataIsMutable();
        data_.set(index, builderForValue.build());
        onChanged();
      } else {
        dataBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     *Data
     * </pre>
     *
     * <code>repeated .Data data = 1;</code>
     */
    public Builder addData(protobuf.java.com.mycompany.blockchain.protobuf.Data value) {
      if (dataBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDataIsMutable();
        data_.add(value);
        onChanged();
      } else {
        dataBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     *Data
     * </pre>
     *
     * <code>repeated .Data data = 1;</code>
     */
    public Builder addData(
        int index, protobuf.java.com.mycompany.blockchain.protobuf.Data value) {
      if (dataBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDataIsMutable();
        data_.add(index, value);
        onChanged();
      } else {
        dataBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     *Data
     * </pre>
     *
     * <code>repeated .Data data = 1;</code>
     */
    public Builder addData(
        protobuf.java.com.mycompany.blockchain.protobuf.Data.Builder builderForValue) {
      if (dataBuilder_ == null) {
        ensureDataIsMutable();
        data_.add(builderForValue.build());
        onChanged();
      } else {
        dataBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     *Data
     * </pre>
     *
     * <code>repeated .Data data = 1;</code>
     */
    public Builder addData(
        int index, protobuf.java.com.mycompany.blockchain.protobuf.Data.Builder builderForValue) {
      if (dataBuilder_ == null) {
        ensureDataIsMutable();
        data_.add(index, builderForValue.build());
        onChanged();
      } else {
        dataBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     *Data
     * </pre>
     *
     * <code>repeated .Data data = 1;</code>
     */
    public Builder addAllData(
        java.lang.Iterable<? extends protobuf.java.com.mycompany.blockchain.protobuf.Data> values) {
      if (dataBuilder_ == null) {
        ensureDataIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, data_);
        onChanged();
      } else {
        dataBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     *Data
     * </pre>
     *
     * <code>repeated .Data data = 1;</code>
     */
    public Builder clearData() {
      if (dataBuilder_ == null) {
        data_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        dataBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     *Data
     * </pre>
     *
     * <code>repeated .Data data = 1;</code>
     */
    public Builder removeData(int index) {
      if (dataBuilder_ == null) {
        ensureDataIsMutable();
        data_.remove(index);
        onChanged();
      } else {
        dataBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     *Data
     * </pre>
     *
     * <code>repeated .Data data = 1;</code>
     */
    public protobuf.java.com.mycompany.blockchain.protobuf.Data.Builder getDataBuilder(
        int index) {
      return getDataFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     *Data
     * </pre>
     *
     * <code>repeated .Data data = 1;</code>
     */
    public protobuf.java.com.mycompany.blockchain.protobuf.DataOrBuilder getDataOrBuilder(
        int index) {
      if (dataBuilder_ == null) {
        return data_.get(index);  } else {
        return dataBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     *Data
     * </pre>
     *
     * <code>repeated .Data data = 1;</code>
     */
    public java.util.List<? extends protobuf.java.com.mycompany.blockchain.protobuf.DataOrBuilder> 
         getDataOrBuilderList() {
      if (dataBuilder_ != null) {
        return dataBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(data_);
      }
    }
    /**
     * <pre>
     *Data
     * </pre>
     *
     * <code>repeated .Data data = 1;</code>
     */
    public protobuf.java.com.mycompany.blockchain.protobuf.Data.Builder addDataBuilder() {
      return getDataFieldBuilder().addBuilder(
          protobuf.java.com.mycompany.blockchain.protobuf.Data.getDefaultInstance());
    }
    /**
     * <pre>
     *Data
     * </pre>
     *
     * <code>repeated .Data data = 1;</code>
     */
    public protobuf.java.com.mycompany.blockchain.protobuf.Data.Builder addDataBuilder(
        int index) {
      return getDataFieldBuilder().addBuilder(
          index, protobuf.java.com.mycompany.blockchain.protobuf.Data.getDefaultInstance());
    }
    /**
     * <pre>
     *Data
     * </pre>
     *
     * <code>repeated .Data data = 1;</code>
     */
    public java.util.List<protobuf.java.com.mycompany.blockchain.protobuf.Data.Builder> 
         getDataBuilderList() {
      return getDataFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        protobuf.java.com.mycompany.blockchain.protobuf.Data, protobuf.java.com.mycompany.blockchain.protobuf.Data.Builder, protobuf.java.com.mycompany.blockchain.protobuf.DataOrBuilder> 
        getDataFieldBuilder() {
      if (dataBuilder_ == null) {
        dataBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            protobuf.java.com.mycompany.blockchain.protobuf.Data, protobuf.java.com.mycompany.blockchain.protobuf.Data.Builder, protobuf.java.com.mycompany.blockchain.protobuf.DataOrBuilder>(
                data_,
                ((bitField0_ & 0x00000001) == 0x00000001),
                getParentForChildren(),
                isClean());
        data_ = null;
      }
      return dataBuilder_;
    }

    private java.lang.Object head_ = "";
    /**
     * <pre>
     *the head
     * </pre>
     *
     * <code>string head = 2;</code>
     */
    public java.lang.String getHead() {
      java.lang.Object ref = head_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        head_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *the head
     * </pre>
     *
     * <code>string head = 2;</code>
     */
    public com.google.protobuf.ByteString
        getHeadBytes() {
      java.lang.Object ref = head_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        head_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *the head
     * </pre>
     *
     * <code>string head = 2;</code>
     */
    public Builder setHead(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      head_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *the head
     * </pre>
     *
     * <code>string head = 2;</code>
     */
    public Builder clearHead() {
      
      head_ = getDefaultInstance().getHead();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *the head
     * </pre>
     *
     * <code>string head = 2;</code>
     */
    public Builder setHeadBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      head_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object link_ = "";
    /**
     * <pre>
     *the link
     * </pre>
     *
     * <code>string link = 3;</code>
     */
    public java.lang.String getLink() {
      java.lang.Object ref = link_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        link_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *the link
     * </pre>
     *
     * <code>string link = 3;</code>
     */
    public com.google.protobuf.ByteString
        getLinkBytes() {
      java.lang.Object ref = link_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        link_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *the link
     * </pre>
     *
     * <code>string link = 3;</code>
     */
    public Builder setLink(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      link_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *the link
     * </pre>
     *
     * <code>string link = 3;</code>
     */
    public Builder clearLink() {
      
      link_ = getDefaultInstance().getLink();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *the link
     * </pre>
     *
     * <code>string link = 3;</code>
     */
    public Builder setLinkBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      link_ = value;
      onChanged();
      return this;
    }

    private protobuf.java.com.mycompany.blockchain.protobuf.Paging paging_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        protobuf.java.com.mycompany.blockchain.protobuf.Paging, protobuf.java.com.mycompany.blockchain.protobuf.Paging.Builder, protobuf.java.com.mycompany.blockchain.protobuf.PagingOrBuilder> pagingBuilder_;
    /**
     * <pre>
     *the price
     * </pre>
     *
     * <code>.Paging paging = 4;</code>
     */
    public boolean hasPaging() {
      return pagingBuilder_ != null || paging_ != null;
    }
    /**
     * <pre>
     *the price
     * </pre>
     *
     * <code>.Paging paging = 4;</code>
     */
    public protobuf.java.com.mycompany.blockchain.protobuf.Paging getPaging() {
      if (pagingBuilder_ == null) {
        return paging_ == null ? protobuf.java.com.mycompany.blockchain.protobuf.Paging.getDefaultInstance() : paging_;
      } else {
        return pagingBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     *the price
     * </pre>
     *
     * <code>.Paging paging = 4;</code>
     */
    public Builder setPaging(protobuf.java.com.mycompany.blockchain.protobuf.Paging value) {
      if (pagingBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        paging_ = value;
        onChanged();
      } else {
        pagingBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     *the price
     * </pre>
     *
     * <code>.Paging paging = 4;</code>
     */
    public Builder setPaging(
        protobuf.java.com.mycompany.blockchain.protobuf.Paging.Builder builderForValue) {
      if (pagingBuilder_ == null) {
        paging_ = builderForValue.build();
        onChanged();
      } else {
        pagingBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     *the price
     * </pre>
     *
     * <code>.Paging paging = 4;</code>
     */
    public Builder mergePaging(protobuf.java.com.mycompany.blockchain.protobuf.Paging value) {
      if (pagingBuilder_ == null) {
        if (paging_ != null) {
          paging_ =
            protobuf.java.com.mycompany.blockchain.protobuf.Paging.newBuilder(paging_).mergeFrom(value).buildPartial();
        } else {
          paging_ = value;
        }
        onChanged();
      } else {
        pagingBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     *the price
     * </pre>
     *
     * <code>.Paging paging = 4;</code>
     */
    public Builder clearPaging() {
      if (pagingBuilder_ == null) {
        paging_ = null;
        onChanged();
      } else {
        paging_ = null;
        pagingBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     *the price
     * </pre>
     *
     * <code>.Paging paging = 4;</code>
     */
    public protobuf.java.com.mycompany.blockchain.protobuf.Paging.Builder getPagingBuilder() {
      
      onChanged();
      return getPagingFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     *the price
     * </pre>
     *
     * <code>.Paging paging = 4;</code>
     */
    public protobuf.java.com.mycompany.blockchain.protobuf.PagingOrBuilder getPagingOrBuilder() {
      if (pagingBuilder_ != null) {
        return pagingBuilder_.getMessageOrBuilder();
      } else {
        return paging_ == null ?
            protobuf.java.com.mycompany.blockchain.protobuf.Paging.getDefaultInstance() : paging_;
      }
    }
    /**
     * <pre>
     *the price
     * </pre>
     *
     * <code>.Paging paging = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        protobuf.java.com.mycompany.blockchain.protobuf.Paging, protobuf.java.com.mycompany.blockchain.protobuf.Paging.Builder, protobuf.java.com.mycompany.blockchain.protobuf.PagingOrBuilder> 
        getPagingFieldBuilder() {
      if (pagingBuilder_ == null) {
        pagingBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            protobuf.java.com.mycompany.blockchain.protobuf.Paging, protobuf.java.com.mycompany.blockchain.protobuf.Paging.Builder, protobuf.java.com.mycompany.blockchain.protobuf.PagingOrBuilder>(
                getPaging(),
                getParentForChildren(),
                isClean());
        paging_ = null;
      }
      return pagingBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:StateData)
  }

  // @@protoc_insertion_point(class_scope:StateData)
  private static final protobuf.java.com.mycompany.blockchain.protobuf.StateData DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new protobuf.java.com.mycompany.blockchain.protobuf.StateData();
  }

  public static protobuf.java.com.mycompany.blockchain.protobuf.StateData getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<StateData>
      PARSER = new com.google.protobuf.AbstractParser<StateData>() {
    public StateData parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new StateData(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<StateData> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<StateData> getParserForType() {
    return PARSER;
  }

  public protobuf.java.com.mycompany.blockchain.protobuf.StateData getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

