# Sawtooth -- Validator Configuration
bind = [
  "network:tcp://10.34.14.1:8800",
  "component:tcp://10.34.14.1:4004"
]

peering = "dynamic"

endpoint = "tcp://10.34.14.1:8800"

scheduler = 'serial'

# A Curve ZMQ key pair are used to create a secured network based on side-band
# sharing of a single network key pair to all participating nodes.
# Note if the config file does not exist or these are not set, the network
# will default to being insecure.
#network_public_key = 'wFMwoOt>yFqI/ek.G[tfMMILHWw#vXB[Sv}>l>i)'
#network_private_key = 'r&oJ5aQDj4+V]p2:Lz70Eu0x#m%IwzBdP(}&hWM*'

# The host and port for Open TSDB database used for metrics
# opentsdb_url = ""

# The name of the database used for storing metrics
# opentsdb_db = ""

# opentsdb_username = ""

# opentsdb_password = ""

# The type of authorization that must be performed for the different type of
# roles on the network. The different supported authorization types are "trust"
# and "challenge". The default is "trust".
[roles]
network = "trust"

# Any off-chain transactor permission roles. The roles should match the roles
# stored in state for transactor permissioning. Due to the roles having . in the
# key, the key must be wrapped in quotes so toml can process it. The value
# should be the file name of a policy stored in the policy_dir.
#[permissions]
#transactor = "policy.example"
#"transactor.transaction_signer" = "policy.example"

# The minimum number of peers required before stopping peer search.
minimum_peer_connectivity = 3

# The maximum number of peers that will be accepted.
maximum_peer_connectivity = 10
